### ISSUE TITLE
Finalize the v0.7 release

### ISSUE THREAD

**Issue by iamh2o** [Daylily-Informatics/daylily#46]
# Objective
- Finalize and announce the `v0.7` release of daylily.

# Tasks
- [ ] Scrub all extraneous `smk` files from the repository.
- [ ] Take a pass at cleaning up the to-be-released `smk`, `script` and other tools.
- [ ] Update the `README.md` to reflect the new release.
- [ ] Update the `CHANGELOG.md` to reflect the new release.
- [ ] Update the `LICENSE` to reflect the new release.
- [ ] scrub all dev documentation, and slim down dramatically.
- [ ] Record install video.
