### ISSUE TITLE
Create v0.7 release

### ISSUE THREAD

**Issue by iamh2o** [Daylily-Informatics/daylily#47]
# Objective
Create a new release for v0.7 & announce.

# Tasks
- [ ] Delete all unused code/docs.
- [ ] Update the README.md file.
- [ ] Draft of whitepaper for v0.7.
- [ ] Roadmap to v0.8.
- [ ] Install video.
